// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYcm7w48khY0fNCnPmRMMFdyYidswCvk8',
    appId: '1:211196681827:web:b6d964a690341a22b9a256',
    messagingSenderId: '211196681827',
    projectId: 'chat-application-707bb',
    authDomain: 'chat-application-707bb.firebaseapp.com',
    storageBucket: 'chat-application-707bb.firebasestorage.app',
    measurementId: 'G-MFF77HB8E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD940g9jBtQxs6A4_BAzTol70Ycbw3G82A',
    appId: '1:211196681827:android:e5c2a4202ba76eceb9a256',
    messagingSenderId: '211196681827',
    projectId: 'chat-application-707bb',
    storageBucket: 'chat-application-707bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvTeT55MnINcFwxHYlDcBTu0Ae2w7hkFY',
    appId: '1:211196681827:ios:816559b9a3f64deeb9a256',
    messagingSenderId: '211196681827',
    projectId: 'chat-application-707bb',
    storageBucket: 'chat-application-707bb.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvTeT55MnINcFwxHYlDcBTu0Ae2w7hkFY',
    appId: '1:211196681827:ios:816559b9a3f64deeb9a256',
    messagingSenderId: '211196681827',
    projectId: 'chat-application-707bb',
    storageBucket: 'chat-application-707bb.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYcm7w48khY0fNCnPmRMMFdyYidswCvk8',
    appId: '1:211196681827:web:a7933856fb3dc993b9a256',
    messagingSenderId: '211196681827',
    projectId: 'chat-application-707bb',
    authDomain: 'chat-application-707bb.firebaseapp.com',
    storageBucket: 'chat-application-707bb.firebasestorage.app',
    measurementId: 'G-49Q6DM57SG',
  );
}
